service: order-app

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-iam-roles-per-function

functions:
  createOrder:
    handler: index.createOrder
    name: create-order
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: orders
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
